spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  redis:
    host: localhost
    port: 6379
